apiVersion: argoproj.io/v1alpha1

kind: Application

metadata:

  name: argo-application

  namespace: argocd

spec:

  project: default

  source:
    
    repoURL: git@github.com:krithiv2012/wordpress.git
    
    targetRevision: HEAD

    path: main

  destination: 

    server: https://kubernetes.default.svc

    namespace: wordpress

  syncPolicy:

    syncOptions:

    - CreateNamespace=true

    automated:

      selfHeal: true

      prune: true